app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'userController@index')->name('index');
Route::get('/cronjob', 'cronjobController@run')->name('cronjob');
//Route::get('/fixingBug', 'cronjobController@fixingBug')->name('fixingBug');




Route::group(['middleware' => ['auth'], 'prefix' => 'admin/users', 'as' => 'admin.users.'], function () {
    Route::get('/{status}', 'UserController@index')->name('index');
    Route::post('init', 'UserController@init')->name('init');
    Route::get('{id}/edit', 'UserController@edit')->name('edit');
    Route::delete('{id}/delete', 'UserController@delete')->name('delete');
    Route::post('{id}/recommission', 'UserController@recommission')->name('recommission');
    Route::get('create', 'UserController@create')->name('create');
    Route::delete('delete_multiple', 'UserController@deleteMultiple')->name('delete_multiple');
    Route::post('store', 'UserController@store')->name('store');
    Route::patch('{id}/update', 'UserController@update')->name('update');
});



Route::group(['middleware' => ['auth'], 'prefix' => "admin/companies", 'as' => "admin.companies."], function () {
    Route::get('/', 'companyController@index')->name('index');
    Route::delete('{id}/delete', 'companyController@delete')->name('delete');
    Route::get('{id}/edit', 'companyController@edit')->name('edit');
    Route::get('init', 'companyController@init')->name('init');
    Route::post('save', 'companyController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/partners", 'as' => "admin.partners."], function () {
    Route::get('/', 'partnerController@index')->name('index');
    Route::delete('{id}/delete', 'partnerController@delete')->name('delete');
    Route::get('{id}/edit', 'partnerController@edit')->name('edit');
    Route::get('init', 'partnerController@init')->name('init');
    Route::post('save', 'partnerController@save')->name('save');

});
Route::group(['middleware' => ['auth'], 'prefix' => "admin/offices", 'as' => "admin.offices."], function () {
    Route::get('/', 'officeController@index')->name('index');
    Route::delete('{id}/delete', 'officeController@delete')->name('delete');
    Route::get('{id}/edit', 'officeController@edit')->name('edit');
    Route::get('init', 'officeController@init')->name('init');
    Route::post('save', 'officeController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/employees", 'as' => "admin.employees."], function () {
    Route::get('/', 'employeeController@index')->name('index');
    Route::delete('{id}/delete', 'employeeController@delete')->name('delete');
    Route::get('{id}/edit', 'employeeController@edit')->name('edit');
    Route::get('init', 'employeeController@init')->name('init');
    Route::post('save', 'employeeController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/sign_ins", 'as' => "admin.sign_ins."], function () {
    Route::get('/', 'sign_in_editingController@index')->name('index');
    Route::get('/no_sign_outs', 'sign_in_editingController@noSignOuts')->name('no_sign_outs');
    Route::delete('{id}/delete', 'sign_in_editingController@delete')->name('delete');
    Route::get('{id}/edit', 'sign_in_editingController@edit')->name('edit');
    Route::get('init', 'sign_in_editingController@init')->name('init');
    Route::post('save', 'sign_in_editingController@save')->name('save');

});
Route::group(['middleware' => ['auth'], 'prefix' => "admin/departments", 'as' => "admin.departments."], function () {
    Route::get('/', 'departmentController@index')->name('index');
    Route::delete('{id}/delete', 'departmentController@delete')->name('delete');
    Route::get('{id}/edit', 'departmentController@edit')->name('edit');
    Route::get('init', 'departmentController@init')->name('init');
    Route::post('save', 'departmentController@save')->name('save');

});
Route::group(['middleware' => ['auth'], 'prefix' => "admin/positions", 'as' => "admin.positions."], function () {
    Route::get('/', 'positionController@index')->name('index');
    Route::delete('{id}/delete', 'positionController@delete')->name('delete');
    Route::get('{id}/edit', 'positionController@edit')->name('edit');
    Route::get('init', 'positionController@init')->name('init');
    Route::post('save', 'positionController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/holidays", 'as' => "admin.holidays."], function () {
    Route::get('/', 'holidayController@index')->name('index');
    Route::delete('{id}/delete', 'holidayController@delete')->name('delete');
    Route::get('{id}/edit', 'holidayController@edit')->name('edit');
    Route::get('init', 'holidayController@init')->name('init');
    Route::post('save', 'holidayController@save')->name('save');

});
Route::group(['middleware' => ['auth'], 'prefix' => "admin/holiday_profiles", 'as' => "admin.holiday_profiles."], function () {
    Route::get('/', 'holiday_profileController@index')->name('index');
    Route::delete('{id}/delete', 'holiday_profileController@delete')->name('delete');
    Route::get('{id}/edit', 'holiday_profileController@edit')->name('edit');
    Route::get('init', 'holiday_profileController@init')->name('init');
    Route::post('save', 'holiday_profileController@save')->name('save');

});
Route::group(['middleware' => ['auth'], 'prefix' => "admin/att_profiles", 'as' => "admin.att_profiles."], function () {
    Route::get('/', 'att_profileController@index')->name('index');
    Route::delete('{id}/delete', 'att_profileController@delete')->name('delete');
    Route::get('{id}/edit', 'att_profileController@edit')->name('edit');
    Route::get('init', 'att_profileController@init')->name('init');
    Route::post('save', 'att_profileController@save')->name('save');

});
Route::group(['middleware' => ['auth'], 'prefix' => "admin/requests", 'as' => "admin.requests."], function () {
    Route::get('/{type}', 'requestController@index')->name('index');
    Route::delete('{id}/delete', 'requestController@delete')->name('delete');
    Route::get('{id}/edit', 'requestController@edit')->name('edit');
    Route::get('init', 'requestController@init')->name('init');
    Route::post('saveEmergency', 'requestController@saveEmergency')->name('saveEmergency');
    Route::post('savePermission', 'requestController@savePermission')->name('savePermission');
    Route::post('saveNormal', 'requestController@saveNormal')->name('saveNormal');
    Route::post('saveFlexHome', 'requestController@saveFlexHome')->name('saveFlexHome');
    Route::post('saveExchangeHome', 'requestController@saveExchangeHome')->name('saveExchangeHome');
    Route::post('saveHalfDay', 'requestController@saveHalfDay')->name('saveHalfDay');
    
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/reqs", 'as' => "admin.reqs."], function () {
    Route::get('/{type}', 'inbound_requestController@index')->name('index');
    Route::get('/user_requests/{user_id}/{status}/{taken}', 'inbound_requestController@userRequests')->name('userRequests');
    Route::delete('{id}/delete', 'inbound_requestController@delete')->name('delete');
    Route::delete('{id}/accept', 'inbound_requestController@accept')->name('accept');
    Route::delete('{id}/reject', 'inbound_requestController@reject')->name('reject');
    Route::delete('{id}/cancel', 'inbound_requestController@cancel')->name('cancel');
    Route::get('init', 'inbound_requestController@init')->name('init');
    Route::post('save', 'inbound_requestController@save')->name('save');
    Route::post('edit_signout_interval', 'inbound_requestController@editSignoutInterval')->name('edit_signout_interval');
    

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/user_reports", 'as' => "admin.user_reports."], function () {
    Route::get('/{type}', 'user_reportController@index')->name('index');
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/sign_in_out", 'as' => "admin.sign_in_out."], function () {
    Route::get('/sign_in', 'sign_inController@sign_in')->name('sign_in');
    Route::get('/sign_out', 'sign_inController@sign_out')->name('sign_out');
    Route::get('/dismissWorkFromHome', 'sign_inController@dismissWorkFromHome')->name('dismissWorkFromHome');
    Route::get('/revertSignOut', 'sign_inController@revertSignOut')->name('revertSignOut');
    Route::get('/refreshSignInOut', 'sign_inController@refreshSignInOut')->name('refreshSignInOut');
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/balance", 'as' => "admin.balance."], function () {
    Route::get('/', 'balanceController@index')->name('index');
    Route::delete('{id}/delete', 'balanceController@delete')->name('delete');
    Route::get('{id}/edit', 'balanceController@edit')->name('edit');
    Route::get('init', 'balanceController@init')->name('init');
    Route::post('save', 'balanceController@save')->name('save');

});
Route::auth();

app/Req.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Req extends Model
{
    protected $table = "requests";

    public function getEmployee(){
    	return $this->hasOne('App\User','id','emp_id');
    }
}

resources/views/reqs/base.blade.php
<?php 
	$i ="inbound_rquests" ; $j = $type;
	
	if($type == "All"){
		
	$i ="user_requests";
	$j = $status;
	if($taken ==1){
		$j=3;
	}
	}
	
	if($type = "Overtime_report"){
		$i = 	"Overtime_report";
	}
 ?>
@extends('admin.master')
@section('plugins_css')
@stop

@section('plugins_js')

@stop

@section('page_js')
@endSection

@section('add_inits')

@stop

@section('title')
Requests
@stop

@section('page_title')
Requests
@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/reqs/edit_form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> New  </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <div  id="main-form" novalidate method="POST" class="larajsval form"> 
            <div class="form-body">
            <div class="mt-element-ribbon bg-grey-steel">
                                                <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                                                    <div class="ribbon-sub ribbon-clip"></div> Main Info </div>
                                                <p class="ribbon-content">
                                                <div class="form-group">
                                                  <div class="form-group">
                    <label>Name</label>
                    <input name="name" class="form-control" value="{{$candidate->name}}">
                    <input type="hidden" name="id" id="hiddenField" value="{{$candidate->id}}" />
                                                  </div>
                <div class="form-group">
                    <label>Email</label>
                    <input name="email" type="email" class="form-control" value="{{$candidate->email}}" >
                </div>
                <div class="form-group">
                    <label>Mobile</label>
                    <input name="mobile" class="form-control" value="{{$candidate->phone}}" >
                </div>
                <div class="form-group">
                    <label>Phase</label>
                    <select name="user_phase" class="form-control" >
                    	<option value="testing" <?php if($candidate->user_phase == "testing"){?> selected="selected"<?php ;}?>>Testing</option>
                    	<option value="testEvaluation" <?php if($candidate->user_phase == "testEvaluation"){?> selected="selected"<?php ;}?>>Test Evaluation</option>
                    	<option value="phoneInterview" <?php if($candidate->user_phase == "phoneInterview"){?> selected="selected"<?php ;}?>>Phone Interview</option>
                    	<option value="pilotTest" <?php if($candidate->user_phase == "pilotTest"){?> selected="selected"<?php ;}?>>Pilot Test</option>
                    	<option value="passedAll" <?php if($candidate->user_phase == "passedAll"){?> selected="selected"<?php ;}?>>Passed All</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Status</label>
                    <select name="user_status" class="form-control" >
                    	<option value="Pending" <?php if($candidate->user_status == "Pending"){?> selected="selected"<?php ;}?>>Pending</option>
                    	<option value="Approved" <?php if($candidate->user_status == "Approved"){?> selected="selected"<?php ;}?>>Approved</option>
                    	<option value="Rejected" <?php if($candidate->user_status == "Rejected"){?> selected="selected"<?php ;}?>>Rejected</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Quiz grade</label>
                    <input name="quiz" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->quiz}}@endif" >
                </div>
                <div class="form-group">
                    <label>Fluency</label>
                    <input name="fluency" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->fluency}}@endif" >
                </div>
                <div class="form-group">
                    <label>Vocab</label>
                    <input name="vocab" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->vocab}}@endif" >
                </div>
                <div class="form-group">
                    <label>Grammar</label>
                    <input name="grammar" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->grammar}}@endif" >
                </div>
                <div class="form-group">
                    <label>Accent</label>
                    <input name="accent" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->accent}}@endif" >
                </div>
                <div class="form-group">
                    <label>Pilot test grade</label>
                    <input name="pilot" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->pilot}}@endif" >
                </div>
               
                
                
                
                
                </p>
                
                                            </div>
                                            
                                            </div>
            

            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    <button type="button" class="btn btn-lg green" id="save-all-edit" data-action="{{route('admin.candidates.saveEdit')}}">Save</button>
                </div>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>

resources/views/reqs/form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> New  </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="{{route('admin.departments.save')}}" method="post" class="ajax_form">
        <div  id="main-form" novalidate method="POST" class="larajsval form"> 
            <div class="form-body">
            <div class="mt-element-ribbon bg-grey-steel">
                                                <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                                                    <div class="ribbon-sub ribbon-clip"></div> Main Info </div>
                                                <p class="ribbon-content">
                                                <div class="form-group">
                                                <div class="form-group">
                                                @if(Auth::user()->role_id == 1)
                                                <div class="form-group">
                    <label>Office</label>
                    <select name="office_id" data-validation="required" data-name="Office" class="form-control">
                    	<option value="">Select Office</option>
                        @foreach($offices as $office)
                    	<option value="{{$office->id}}" <?php if($office->id == $department->office_id){?>selected<?php ;}?>>{{$office->name}}</option>
                        @endforeach
                    </select>
                    <span class="error_message"></span>
                </div>
                								@endif
                                                @if(Auth::user()->role_id == 2)
                    							<input type="hidden" name="office_id" id="office_id" value="{{Auth::user()->office_id}}"  data-validation="" data-name="office_id"  />
                								@endif
                                                  <div class="form-group">
                    <label>Name</label>
                    <input type="hidden" name="company_id"  data-validation="" data-name="company_id" value="{{Auth::user()->company_id}}"/>
                    <input name="name" class="form-control" data-validation="required" data-name="Name" value="{{$department->name}}" >
                    <span class="error_message"></span>
                    <input type="hidden" name="id" id="hiddenField" value="{{$department->id}}" data-validation="" data-name="id" />
                                                  </div>
                
                
                
                
                
                </p>
                
                                            </div>
                                            
                                            </div>
            

            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    <button type="submit" class="btn btn-lg green"  >Save</button>
                </div>
            </div>
        </div>
        <input type="reset" class="hide resetForm" >
        </form>
        <!-- END FORM-->
    </div>
</div>

resources/views/reqs/list.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>{{$type}}
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
      <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                                    
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt" >
            <thead>
                <tr class="tr-head">
                  <th valign="middle">Employee</th>
                  <th valign="middle">Type</th>
                  <?php if($type == "Permissions"  || $type == "All" || $type == "Half Day" || $type == "Home" || $type == "Overtime"){?>
                  <th valign="middle">Day</th>
                  <?php ;}?>
                  <?php if($type == "Permissions"  || $type == "All" || $type == "Overtime" || $type == "Normal Leaves" || $type == "Emergency Leaves"){?>
                  <th valign="middle">From </th>
                  <th valign="middle">To </th>
                  <th valign="middle">Interval</th>
                  <?php ;}?>
                  
                  <?php if($type == "Half Day"  || $type == "All" || $type == "Home"){?>
                  <th valign="middle">
                  @if($type == "Half Day")
                  	Half
                    @endif
                    @if($type == "Home")
                  	Exchanged day
                    @endif
                    @if($type == "All")
                    	Notes
                    @endif
                  </th>
                  <?php ;}?>
                  <th valign="middle">
                      Requested at
                  </th>
                  <th valign="middle">Status</th>
                    <th valign="middle">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($reqs as $req)
                <tr class="odd gradeX" id="data-row-{{$req->id}}">
                  <td valign="middle">
                  {{$req->name}}
                      
                    </td>
                  <td valign="middle">
                  	<?php $req_type = str_replace("ves","ve",$req->type);
						$req_type= str_replace("ns","n",$req_type);
						echo str_replace("Home","Work From Home",$req_type);
					?>
                  </td>
                  <?php if($type == "Permissions"  || $type == "All" || $type == "Half Day"  || $type == "Home" || $type == "Overtime"){?>
                  <td valign="middle">{{$req->req_day}}</td>
                  <?php ;}?>
                  <?php if($type == "Permissions"  || $type == "All" || $type == "Overtime" || $type == "Normal Leaves" || $type == "Emergency Leaves"){?>
                  <td valign="middle">
                  <?php if($req->type == "Emergency Leaves" || $req->type == "Normal Leaves"){?>
                  <?php echo date("Y-m-d",strtotime($req->time_from));?>
                  <?php ;}else{?>
                  {{$req->time_from}}
                  <?php ;}?>
                  
                  </td>
                  <td valign="middle">
                  <?php if($req->type == "Emergency Leaves" || $req->type == "Normal Leaves"){?>
                  <?php echo date("Y-m-d",strtotime($req->time_to));?>
                  <?php ;}else{?>
                  {{$req->time_to}}
                  <?php ;}?>
                  
                  
                  </td>
                  <td valign="middle">
				  <?php if(isset($req->interval_in_days)){?>
                  {{$req->interval_in_days}} Day(s)
                  <?php ;}?>
                   <?php if(isset($req->interval_in_time)){?>
                  {{$req->interval_in_time}}
                  <?php ;}?>
				  <?php if($req->type == "Overtime" && $req->status == 2){?>
                  <form action="{{route('admin.reqs.edit_signout_interval')}}" method="post" class="ajax_form">
                  <input type="hidden" name="id" value="{{$req->id}}" />
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="left" valign="middle"><input name="interval_in_time" class="form-control timepicker timepicker-24" data-validation="required" data-name="From" value="{{$req->interval_in_time}}" >
                  <span class="error_message"></span></td>
    <td width="50" align="left" valign="middle"><button type="submit" class="btn btn-lg green"  ><i class="fa fa-check"></i></button></td>
  </tr>
</table>

                  
                    
                  </form>
                  <?php ;}?>
                  
				  </td>
                  <?php ;}?>
                  
                  <?php if($type == "Half Day" || $type == "Home" || $type == "All"){?>
                  <td valign="middle">{{$req->add_info}}</td>
                  <?php ;}?>
                  <td valign="middle">
                      {{$req->created_at}}
                    </td>
                  <td valign="middle">
				  <?php $req_status = str_replace("1","Accepted", $req->status);
				  		$req_status = str_replace("2","Pending", $req_status);
						echo str_replace("0","Rejected", $req_status);
				  ?>
				  
				  </td>
                    <td valign="middle">
                    @if($req->status == 2 && $type != "All")
                        <a href="#" data-action="{{route('admin.reqs.accept',['id'=>$req->id])}}" class="btn green delete_single" ><i class="fa fa-check"></i> Accept</a> 
                        <a href="#" data-action="{{route('admin.reqs.reject',['id'=>$req->id])}}" class="btn red delete_single" ><i class="fa fa-remove"></i> Reject</a> 
                        @endif
                        @if(($req->status == 2 || $req->status == 1) && ($type == "All" && $req->taken == 0) )
                        <a href="#" data-action="{{route('admin.reqs.cancel',['id'=>$req->id])}}" class="btn red delete_single" ><i class="fa fa-remove"></i> Cancel Request</a> 
                        
                        @endif
                    </td>
                </tr>
                @endforeach
                

        </table>
    </div>
</div>

resources/views/reqs/test_details.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Test Details
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                           <a href="{{route('admin.candidates.add')}}" class="pjax-link"><button class="btn green" >

                            Add New Candidate <i class="fa fa-plus"></i>
                        </button>
                        </a>                  
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt" >
            <thead>
                <tr class="tr-head">
                    <th valign="middle">Question</th>
                    <th valign="middle">Student Degree</th>
                    <th valign="middle">Max degree</th>
                    <th valign="middle">Start time</th>
                    <th valign="middle">End time</th>
                </tr>
            </thead>
            <tbody>
                @foreach($answers as $answer)
                <tr class="odd gradeX" id="data-row-{{$answer->id}}" data-user_id = "{{$answer->id}}">
                    <td valign="middle">
                    {{$answer->getQuestion->content}}
                        
                    </td>
                    <td valign="middle">{{$answer->degree}}</td>
                    <td valign="middle">{{$answer->getQuestion->weight}}</td>
                    <td valign="middle">{{$answer->getEntry->start_time}}</td>
                    <td valign="middle">{{$answer->getEntry->end_time}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/reqs/view.blade.php
	<iframe width="100%" height="1000" src="{{$path}}" frameborder="0" scrolling="no"></iframe>